config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/sign-out', to: 'devise/sessions#destroy', via: :delete, as: :sign_out_session
  end

  devise_for :users, :skip => [:sessions]
as :user do 
    get '/sign-in', to: 'devise/sessions#new'
    post '/sign-in', to: 'devise/sessions#create'    
    delete '/sign-out', to: 'devise/registrations#destroy', as: 'sign_out'
    get 'edit', to: 'devise/registrations#edit', as: 'edit'
  end

  resources :user_friendships do
  end

  resources :statuses
  get 'feed', to: "statuses#index", as: 'feed'
  root to: 'welcome#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                            format: {
                            with: /\A\S*\Z/,
                            message: 'Must be formatted correctly.'
                          }

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships
  
  def full_name
    first_name + " " + last_name
  end

  def to_param
    profile_name
  end
  
  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)
    @status.user = current_user

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id,:content)
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_filter :authenticate_user!, only: [:new]

  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] = "Friend required"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

  def create
    if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
      @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
      @user_friendship = current_user.user_friendships.new(friend: @friend)
      if @user_friendship.save
        flash[:success] = "Friendship created."
      else
        flash[:error] = "There was a problem."
      end
      redirect_to profile_path(@friend)
    else
      flash[:error] = "Friend required"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


def index
	
end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when 'alert'
			'label-error'
		when 'notice'
		    'label-success'
		else
		     ''
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.</p>
</footer>

app/views/layouts/_navbar.html.erb
<header class="centered-navigation">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
      <li class="nav-link"><a href="javascript:void(0)">Products</a></li>
      <li class="nav-link"><a href="javascript:void(0)">About Us</a></li>
      <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
      <li class="nav-link logo">
        <a href="javascript:void(0)" class="logo">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
        </a>
      </li>
      <li class="nav-link"><a href="javascript:void(0)">Testimonials</a></li>
      <li class="nav-link more"><a href="javascript:void(0)">More</a>
        <ul class="submenu">
          <li><a href="javascript:void(0)">Submenu Item</a></li>
          <li><a href="javascript:void(0)">Another Item</a></li>
          <li class="more"><a href="javascript:void(0)">Item with submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
              <li><a href="javascript:void(0)">Another Item</a></li>
            </ul>
          </li>
          <li class="more"><a href="javascript:void(0)">Another submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu</a></li>
              <li><a href="javascript:void(0)">An Item</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="nav-link"><a href="javascript:void(0)">Sign up</a></li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minstrel2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Nunito:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <article class="type-system-rounded">
   <header class="centered-navigation">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
      <li class="nav-link"><a href="javascript:void(0)">Popular</a></li>
      <li class="nav-link"><%= link_to "Feed", feed_path %></li>
       <% if current_user %>
        <li class="nav-link">
          <%= link_to "My Profile", profile_path(current_user.profile_name) %>
        </li>
      <% else %>
      <% end %>
      <li class="nav-link logo">
      </li>
      <li class="nav-link"><a href="javascript:void(0)">Bands</a></li>
      <li class="nav-link more"><a href="javascript:void(0)">Genres</a>
        <ul class="submenu">
          <li><a href="javascript:void(0)">Rock</a></li>
          <li><a href="javascript:void(0)">Pop</a></li>
          <li class="more"><a href="javascript:void(0)">Item with submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
              <li><a href="javascript:void(0)">Another Item</a></li>
            </ul>
          </li>
          <li class="more"><a href="javascript:void(0)">Another submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu</a></li>
              <li><a href="javascript:void(0)">An Item</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <% if user_signed_in? %>
        <li class="nav-link">
          <%= link_to current_user.full_name, edit_path %>
          <li class="nav-link"><%= link_to 'Log Out', sign_out_path %></li>
        <% else %>
          <li class="nav-link">
            <%= link_to "Sign In", sign_in_path %>
          </li>
          <li class="nav-link">
            <%= link_to "Register", register_path %>
          </li>
        <%end%>   
        </li>
    </ul>
  </div>
</header>
    <div class="main-container">

      <%if flash[:notice] %>
        <label class="label-success">
          <%= flash[:notice] %>
        </label>
      <% end %>

      <%if flash[:alert] %>
        <label class="label-error">
          <%= flash[:alert] %>
        </label>
      <% end %>

      <%= yield %>
    </div>
  </article>
</body>  
</html>

app/views/profiles/show.html.erb
<!-- <div class="page-header">
  <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user) %>
</div> -->



<div class="hero">
  <div class="hero-inner">
    <div class="hero-copy">
      <% if @statuses %>
      <% @statuses.each do |status| %>
        
        <div class="comment">
          <div class="comment-image">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
          </div>
          <div class="comment-content">
            <h1><%= @user.full_name %></h1>
            <p><%= status.content %></p>
            <p class="comment-detail"><%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago</p>
          </div>
        </div>
        <script src="app/assets/stylesheets/chat.js">
          <video id="player" autoplay="true"></video>
        </script>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/refills/_SNIPPET.html.erb
<div class="snippet">
  <a href="#" class="copy-source">Copy</a>
  <pre><code class="language-<%= language %>"><%== snippet %></code></pre>
</div>

app/views/statuses/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.</p>
</footer>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <div class="forms">
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="profile_name">
  <br>
  </div>
  <%= f.input :content %>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/statuses/_navbar.html.erb
<header class="centered-navigation">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
      <li class="nav-link"><a href="javascript:void(0)">Popular</a></li>
      <li class="nav-link"><a href="javascript:void(0)">Status</a></li>
      <li class="nav-link"><a href="javascript:void(0)">My Profile</a></li>
      <li class="nav-link logo">
        <a href="javascript:void(0)" class="logo">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
        </a>
      </li>
      <li class="nav-link"><a href="javascript:void(0)">Bands</a></li>
      <li class="nav-link more"><a href="javascript:void(0)">Genres</a>
        <ul class="submenu">
          <li><a href="javascript:void(0)">Rock</a></li>
          <li><a href="javascript:void(0)">Pop</a></li>
          <li class="more"><a href="javascript:void(0)">Item with submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
              <li><a href="javascript:void(0)">Another Item</a></li>
            </ul>
          </li>
          <li class="more"><a href="javascript:void(0)">Another submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu</a></li>
              <li><a href="javascript:void(0)">An Item</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="nav-link"><%= link_to current_user.full_name, edit_user_registration_path %></li>
    </ul>
  </div>
</header>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Minstrel</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  
<% if @statuses %>  
  </thead>

  <tbody>
  
    <% @statuses.each do |status| %>
    <tr>
        <td><%= link_to status.user.full_name, profile_path(status.user.profile_name) %></td>
        <td><%= link_to status.content, status%></td>
        <% if user_signed_in? && status.user_id == current_user %>
          <td><%= link_to 'Edit', edit_status_path(status) %></td>
          <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%end%>
<% if current_user %>
  <%= link_to 'New Status', new_status_path %>
<% else %>
  <%= link_to "Make A Profile, It's Easy!", register_path %>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p>
  <strong><%= @status.user.full_name %></strong>
  
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/user_friendships/new.html.erb
<% if flash[:error] %>
Not found.
<% else %>
<div class="page-header">
  <h1><%= @friend.full_name %></h1>
</div>

<p>
  Do you really want to friend <%= @friend.full_name %>?
</p>


  <div class="modal">
    <label for="modal-1">
      <div class="modal-trigger">Send Friend Request</div>
    </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
    <div class="modal-window">
      <div class="modal-inner">
        <label class="modal-close" for="modal-1"></label>
         <h1>Are You sure?</h1>
       <%= form_for @user_friendship, method: :post do |form| %>
    <div class="form form-actions">
      <%= form.hidden_field :friend_id, value: @friend.profile_name %>
      <%= submit_tag "Yes, Add Friend", class: 'friend_button' %>
    </div>
  <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="hero">
	<div class="hero-inner">
		<div class="hero-copy">
			<h1 class="minstrel">Minstrel</h1>
			<p>Minstrel lets fans and musicians interact in a neat way. Fans can view artist profiles and check out their songs, if they like what they see, they may follow this musician. This allows instant acecess to request a live mini-performance. If the musician is available, the two can then connect via Minstrel! Hit it off or launch right into the performance, that's up to you! Minstrel's goal is to connect musicans and Fans in our busy lifestyles, music has always been a big part of human nature, and we believe it always will!</p>	
		</div>
    <button><%= link_to "Make A Profile, It's Easy!", register_path, class: "wlcome"%></button>
	</div>
</div>